// Each section's specific fields for the 26-step architectural analysis
export const SECTION_FIELDS: Record<string, { label: string; placeholder: string; type: "text" | "textarea" | "select"; options?: string[] }[]> = {
  identification: [
    { label: "Nom du projet", placeholder: "Ex: Complexe Résidentiel Al Boustane", type: "text" },
    { label: "Maître d'ouvrage", placeholder: "Nom du commanditaire", type: "text" },
    { label: "Architecte responsable", placeholder: "Nom de l'architecte", type: "text" },
    { label: "Superficie du terrain (m²)", placeholder: "Ex: 2500", type: "text" },
    { label: "Type de projet", placeholder: "Sélectionnez", type: "select", options: ["Résidentiel", "Commercial", "Mixte", "Industriel", "Équipement public", "Autre"] },
    { label: "Notes complémentaires", placeholder: "Informations administratives supplémentaires...", type: "textarea" },
  ],
  localisation: [
    { label: "Ville", placeholder: "Ex: Casablanca", type: "text" },
    { label: "Quartier / Arrondissement", placeholder: "Ex: Maarif", type: "text" },
    { label: "Adresse exacte", placeholder: "Adresse complète du terrain", type: "textarea" },
    { label: "Contexte urbain", placeholder: "Centre-ville, périphérie, zone rurale...", type: "select", options: ["Centre-ville", "Périurbain", "Zone industrielle", "Zone rurale", "Littoral"] },
    { label: "Notes sur le contexte", placeholder: "Description du quartier, limites...", type: "textarea" },
  ],
  accessibilite: [
    { label: "Voies principales à proximité", placeholder: "Ex: Boulevard Zerktouni, Autoroute A3...", type: "textarea" },
    { label: "Transports en commun", placeholder: "Tramway, bus, gare...", type: "textarea" },
    { label: "Qualité de desserte", placeholder: "Sélectionnez", type: "select", options: ["Excellente", "Bonne", "Moyenne", "Faible", "Très faible"] },
    { label: "Stationnement existant", placeholder: "Parking, voirie, capacité...", type: "textarea" },
    { label: "Accessibilité piétonne", placeholder: "Trottoirs, passages piétons, pistes cyclables...", type: "textarea" },
  ],
  environnement: [
    { label: "Bâtiments voisins (Nord)", placeholder: "Type, hauteur, usage...", type: "textarea" },
    { label: "Bâtiments voisins (Sud)", placeholder: "Type, hauteur, usage...", type: "textarea" },
    { label: "Bâtiments voisins (Est)", placeholder: "Type, hauteur, usage...", type: "textarea" },
    { label: "Bâtiments voisins (Ouest)", placeholder: "Type, hauteur, usage...", type: "textarea" },
    { label: "Équipements à proximité", placeholder: "Écoles, mosquées, hôpitaux, commerces...", type: "textarea" },
  ],
  topographie: [
    { label: "Type de relief", placeholder: "Sélectionnez", type: "select", options: ["Plat", "Légère pente", "Pente modérée", "Forte pente", "Terrain accidenté"] },
    { label: "Dénivelé estimé (m)", placeholder: "Ex: 3.5", type: "text" },
    { label: "Orientation de la pente", placeholder: "Sélectionnez", type: "select", options: ["Nord", "Sud", "Est", "Ouest", "Nord-Est", "Nord-Ouest", "Sud-Est", "Sud-Ouest"] },
    { label: "Impact sur le projet", placeholder: "Terrassement nécessaire, contraintes...", type: "textarea" },
  ],
  geologie: [
    { label: "Nature du sol", placeholder: "Sélectionnez", type: "select", options: ["Argileux", "Sablonneux", "Rocheux", "Limoneux", "Calcaire", "Mixte"] },
    { label: "Capacité portante estimée", placeholder: "Ex: Bonne, nécessite étude géotechnique...", type: "text" },
    { label: "Nappe phréatique", placeholder: "Profondeur estimée, risques...", type: "textarea" },
    { label: "Risques géologiques", placeholder: "Glissements, séismes, affaissements...", type: "textarea" },
  ],
  climat: [
    { label: "Zone climatique", placeholder: "Sélectionnez", type: "select", options: ["Méditerranéen", "Semi-aride", "Aride", "Océanique", "Continental", "Montagnard"] },
    { label: "Température moyenne annuelle (°C)", placeholder: "Ex: 18.5", type: "text" },
    { label: "Pluviométrie annuelle (mm)", placeholder: "Ex: 400", type: "text" },
    { label: "Vents dominants", placeholder: "Direction, intensité, saisonnalité...", type: "textarea" },
    { label: "Microclimats observés", placeholder: "Effet d'îlot de chaleur, corridors de vent...", type: "textarea" },
  ],
  orientation: [
    { label: "Orientation principale de la façade", placeholder: "Sélectionnez", type: "select", options: ["Nord", "Sud", "Est", "Ouest", "Nord-Est", "Nord-Ouest", "Sud-Est", "Sud-Ouest"] },
    { label: "Durée d'ensoleillement (h/jour en été)", placeholder: "Ex: 10", type: "text" },
    { label: "Masques solaires", placeholder: "Bâtiments ou éléments bloquant le soleil...", type: "textarea" },
    { label: "Stratégie bioclimatique recommandée", placeholder: "Protection solaire, captage passif...", type: "textarea" },
  ],
  vues: [
    { label: "Vues remarquables", placeholder: "Panoramas, monuments, mer, montagne...", type: "textarea" },
    { label: "Vues à préserver", placeholder: "Perspectives à protéger dans la conception...", type: "textarea" },
    { label: "Vues à éviter", placeholder: "Zones industrielles, décharges, nuisances visuelles...", type: "textarea" },
  ],
  sonore: [
    { label: "Niveau de bruit ambiant", placeholder: "Sélectionnez", type: "select", options: ["Très calme", "Calme", "Modéré", "Bruyant", "Très bruyant"] },
    { label: "Sources de bruit principales", placeholder: "Trafic, industrie, aéroport...", type: "textarea" },
    { label: "Mesures d'atténuation recommandées", placeholder: "Isolation, murs anti-bruit, végétation...", type: "textarea" },
  ],
  qualiteAir: [
    { label: "Qualité de l'air estimée", placeholder: "Sélectionnez", type: "select", options: ["Excellente", "Bonne", "Acceptable", "Médiocre", "Mauvaise"] },
    { label: "Sources de pollution", placeholder: "Industries, trafic routier, chantiers...", type: "textarea" },
    { label: "Ventilation naturelle", placeholder: "Corridors de vent, orientation favorable...", type: "textarea" },
  ],
  vegetation: [
    { label: "Type de végétation existante", placeholder: "Arbres, arbustes, pelouse, friche...", type: "textarea" },
    { label: "Espèces remarquables", placeholder: "Arbres centenaires, espèces protégées...", type: "textarea" },
    { label: "Végétation à conserver", placeholder: "Éléments à intégrer dans le projet...", type: "textarea" },
  ],
  hydrologie: [
    { label: "Cours d'eau à proximité", placeholder: "Oueds, rivières, canaux...", type: "textarea" },
    { label: "Risque d'inondation", placeholder: "Sélectionnez", type: "select", options: ["Nul", "Faible", "Modéré", "Élevé", "Très élevé"] },
    { label: "Réseau de drainage existant", placeholder: "Caniveaux, fossés, bassins de rétention...", type: "textarea" },
  ],
  reseaux: [
    { label: "Eau potable", placeholder: "Sélectionnez", type: "select", options: ["Disponible sur site", "Raccordement nécessaire", "Non disponible"] },
    { label: "Assainissement", placeholder: "Sélectionnez", type: "select", options: ["Réseau collectif", "Fosse septique", "Non disponible"] },
    { label: "Électricité", placeholder: "Sélectionnez", type: "select", options: ["Disponible sur site", "Raccordement nécessaire", "Non disponible"] },
    { label: "Télécommunications", placeholder: "Fibre, ADSL, réseau mobile...", type: "textarea" },
    { label: "Notes sur les réseaux", placeholder: "Capacité, état, contraintes de raccordement...", type: "textarea" },
  ],
  reglementation: [
    { label: "Zone du PLU/PA", placeholder: "Ex: Zone UB, Zone NA...", type: "text" },
    { label: "COS (Coefficient d'Occupation du Sol)", placeholder: "Ex: 0.6", type: "text" },
    { label: "CES (Coefficient d'Emprise au Sol)", placeholder: "Ex: 0.4", type: "text" },
    { label: "Hauteur maximale autorisée (m)", placeholder: "Ex: 15", type: "text" },
    { label: "Reculs réglementaires", placeholder: "Alignement, marges, prospects...", type: "textarea" },
    { label: "Servitudes", placeholder: "Passages, canalisations, protections...", type: "textarea" },
  ],
  morphologie: [
    { label: "Type de tissu urbain", placeholder: "Sélectionnez", type: "select", options: ["Traditionnel dense", "Moderne planifié", "Pavillonnaire", "Grands ensembles", "Mixte", "Informel"] },
    { label: "Hauteur moyenne des bâtiments (étages)", placeholder: "Ex: R+3", type: "text" },
    { label: "Typologies dominantes", placeholder: "Villas, immeubles, riads, commerces...", type: "textarea" },
    { label: "Densité urbaine observée", placeholder: "Sélectionnez", type: "select", options: ["Très dense", "Dense", "Modérée", "Faible", "Très faible"] },
  ],
  fonctionnelle: [
    { label: "Usages actuels du terrain", placeholder: "Terrain vague, agriculture, bâti existant...", type: "textarea" },
    { label: "Usages des parcelles voisines", placeholder: "Résidentiel, commercial, industriel...", type: "textarea" },
    { label: "Compatibilité fonctionnelle", placeholder: "Conflits d'usage, complémentarités...", type: "textarea" },
  ],
  flux: [
    { label: "Flux piétons", placeholder: "Sélectionnez", type: "select", options: ["Très fréquenté", "Fréquenté", "Modéré", "Faible", "Quasi inexistant"] },
    { label: "Flux véhiculaires", placeholder: "Sélectionnez", type: "select", options: ["Très dense", "Dense", "Modéré", "Faible", "Très faible"] },
    { label: "Heures de pointe observées", placeholder: "Matin, midi, soir...", type: "textarea" },
    { label: "Points de congestion", placeholder: "Carrefours, accès, zones d'engorgement...", type: "textarea" },
  ],
  socioEco: [
    { label: "Profil socio-économique du quartier", placeholder: "Sélectionnez", type: "select", options: ["Haut standing", "Classe moyenne supérieure", "Classe moyenne", "Populaire", "Mixte"] },
    { label: "Activités économiques dominantes", placeholder: "Commerce, services, artisanat...", type: "textarea" },
    { label: "Équipements sociaux", placeholder: "Écoles, centres de santé, espaces culturels...", type: "textarea" },
    { label: "Tendances de développement", placeholder: "Gentrification, expansion, stagnation...", type: "textarea" },
  ],
  identiteArch: [
    { label: "Style architectural dominant", placeholder: "Sélectionnez", type: "select", options: ["Traditionnel marocain", "Art déco colonial", "Moderne", "Contemporain", "Mixte", "Sans identité marquée"] },
    { label: "Matériaux dominants", placeholder: "Pierre, béton, brique, bois, zellige...", type: "textarea" },
    { label: "Patrimoine architectural", placeholder: "Monuments classés, bâtiments historiques...", type: "textarea" },
    { label: "Recommandations d'intégration", placeholder: "Comment s'inscrire dans le tissu existant...", type: "textarea" },
  ],
  paysage: [
    { label: "Qualité paysagère globale", placeholder: "Sélectionnez", type: "select", options: ["Remarquable", "Bonne", "Moyenne", "Médiocre", "Dégradée"] },
    { label: "Éléments paysagers remarquables", placeholder: "Arbres monumentaux, perspectives, skyline...", type: "textarea" },
    { label: "Points noirs paysagers", placeholder: "Friches, décharges, constructions anarchiques...", type: "textarea" },
  ],
  environnementale: [
    { label: "Sensibilité écologique du site", placeholder: "Sélectionnez", type: "select", options: ["Très sensible", "Sensible", "Modérée", "Faible", "Non sensible"] },
    { label: "Risques naturels identifiés", placeholder: "Inondation, séisme, glissement, érosion...", type: "textarea" },
    { label: "Potentiel d'énergie renouvelable", placeholder: "Solaire, éolien, géothermie...", type: "textarea" },
    { label: "Mesures environnementales recommandées", placeholder: "Gestion des eaux, matériaux écologiques...", type: "textarea" },
  ],
  contraintes: [
    { label: "Contraintes réglementaires", placeholder: "Zones non aedificandi, servitudes...", type: "textarea" },
    { label: "Contraintes physiques", placeholder: "Pente, sol, nappe phréatique...", type: "textarea" },
    { label: "Contraintes environnementales", placeholder: "Bruit, pollution, risques naturels...", type: "textarea" },
    { label: "Contraintes sociales", placeholder: "Opposition, usages informels, droits coutumiers...", type: "textarea" },
  ],
  opportunites: [
    { label: "Atouts du site", placeholder: "Emplacement, vues, desserte...", type: "textarea" },
    { label: "Potentiel de développement", placeholder: "Densification, mixité, innovation...", type: "textarea" },
    { label: "Programmes complémentaires envisageables", placeholder: "Commerce, bureau, espace vert...", type: "textarea" },
  ],
  swot: [
    { label: "Forces (Strengths)", placeholder: "Atouts majeurs du site...", type: "textarea" },
    { label: "Faiblesses (Weaknesses)", placeholder: "Points faibles à compenser...", type: "textarea" },
    { label: "Opportunités (Opportunities)", placeholder: "Tendances et potentiels à exploiter...", type: "textarea" },
    { label: "Menaces (Threats)", placeholder: "Risques et dangers à anticiper...", type: "textarea" },
  ],
  synthese: [
    { label: "Synthèse globale de l'analyse", placeholder: "Résumé des conclusions principales de l'analyse de site...", type: "textarea" },
    { label: "Recommandations architecturales", placeholder: "Orientations pour la conception du projet...", type: "textarea" },
    { label: "Parti architectural proposé", placeholder: "Vision générale et principes directeurs...", type: "textarea" },
  ],
};
